spring.application.name=todoapi
server.port=8080

spring.data.mongodb.uri=mongodb+srv://nkemkahchukwudubem_db_user:w4yVqBmCPSGzLDc6@cluster0.v7hftln.mongodb.net/tododb?retryWrites=true&w=majority

app.jwt.secret=3f8b2c1d9e7a4f6b0c5d2e8a1b7f4c9d3e6a0b5f2c8d1e7a4b9f3c6d0e5a2b8
app.jwt.expiration=86400000

jwt.secret=zDhWGo3h3G6OJwV1f4PrVKgfpPj7uCoH0xsLLKGhq/U=
jwt.expiration=86400000

logging.level.com.david.todoapi=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.root=DEBUG